name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: jshim0978/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.PRODUCTIVE_BOX }}	
          GIST_ID: 5ba63bfd6fbb255f838fec68c223d17e
          TIMEZONE: Asia/Taipei
